name: testing-workflows

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  print-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print file contents
        run: |
          cat ${{ github.action_path }}/settings.xml
